# Generated by Django 2.2.26 on 2022-01-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aghjh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kj', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lhkj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jb', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sgchg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kh', models.CharField(max_length=256)),
            ],
        ),
    ]
