# Generated by Django 2.2.26 on 2022-01-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_aghjh_lhkj_sgchg"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ahkj",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jkj", models.BigIntegerField()),
            ],
        ),
    ]
